
permalink: /:categories/:year/:month/:day/:title.html

language: en
license:
  url: https://creativecommons.org/licenses/by-sa/4.0/
  message: |
    This work is licensed under the <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

url: http://minglis.id.au
author:
    name: Malcolm Inglis
    email: me@minglis.id.au
    github: mcinglis
    tagline: 'software developer'
    location: 'Seattle'
    location_url: 'https://en.wikipedia.org/wiki/Seattle'

